### ISSUE TITLE
REQ: Allow custom Board server / URL

### ISSUE THREAD

**Issue by Quackdoc** [FerrahWolfeh/imageboard-downloader-rs#6]
Since there are a lot of image boards around but most of them share the same board software as others, it would be really nice if we could do something like `imageboard_downloader -s moebooru -i https://yande.re ...` this would help a lot instead of needing to hard code many sites that may not be popular.

as for custom syntax, maybe regex? 

Instead of hoping it works out well, perhaps a config file might be better and more flexible?
```toml
#based on konachan
[yandere]
server = "moebooru"
useragent = ""
extractor_user_agent = ""
base_url = "https://yande.re"
post_url = ""
post_list_url = "https://yande.re/post.json"
pool_idx_url = ""
max_post_limit = 100
auth_url = ""
```
